# Generated by Django 3.1.1 on 2020-09-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField(default=uuid.UUID('48986eaf-811a-4b64-95f1-142236ce5d58'), editable=False)),
                ('update_user', models.UUIDField(default=uuid.UUID('fba67b55-383d-455e-862c-3ac8df614ce7'), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField(default=uuid.UUID('057ff1ed-c230-4600-9fd1-99492719a89b'), editable=False)),
                ('update_user', models.UUIDField(default=uuid.UUID('e838368c-8039-4f0c-8e08-304e3a85ab94'), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phone', models.CharField(default='Sem Telefone', max_length=14)),
                ('role', models.CharField(default='Sem Atribuição', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('joining_date', models.DateField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField(default=uuid.UUID('3f8658c0-b59d-4a93-806b-fc3e32ec56eb'), editable=False)),
                ('update_user', models.UUIDField(default=uuid.UUID('6e87b72e-3b18-4ef3-b26c-fe4aca9becc1'), editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
